### ISSUE TITLE
Change brand hyperlink in the navbar

### ISSUE THREAD

**Issue by hesamd** [evenset/ketabdan-project#26]
- [ ] Currently, those hyperlinks do nothing, change them in a way to redirect the user to the homepage. You can test it by going to register and then click on the brand.
- [ ] Also remove the Home menu from the Navbar

**Comment by maryamyasaei** [comment]
Actually, you mean those hyperlinks under dropdown menu? and what do you mean by "brand" when you said click on the brand.

**Comment by hesamd** [comment]
I meant brand and home links. Check navbar HTML code and you will find what brand is.

**Comment by maryamyasaei** [comment]
Done..

**Comment by maryamyasaei** [comment]
Already I put "localhost:800" , then later we can put the real url..

**Comment by hesamd** [comment]
1. It's `localhost:8000` and not `localhost:800`
2. I don't see any pull request so I can't tell if your push was correct
3. localhost will break the production, hence you should use relative urls instead of an absolute one

**Comment by maryamyasaei** [comment]
1- 800 was typo :)
2 - what do you mean by relative url?

**Comment by maryamyasaei** [comment]
Done ..
