### ISSUE TITLE
Shortstories app model

### ISSUE THREAD

**Issue by hesamd** [evenset/ketabdan-project#28]
- [x] Create a new app called `shortstories` , [how to create django app](https://docs.djangoproject.com/en/2.0/intro/tutorial01/#creating-the-polls-app)
- [x]  Inside `shortstories` create a new model called `Shortstory` [Guide](https://docs.djangoproject.com/en/2.0/intro/tutorial02/#creating-models). The model has different fields, `author` which is foreign key to the user, `title` which is charfield with max 500 length, `body` with min length 3500, `status` choice field of ('draft', 'published', 'banned', 'deleted' and `publication_date` 
- [x] complete the above check mark, push your code and wait for review
-  [x] Activate you app/model [guide](https://docs.djangoproject.com/en/2.0/intro/tutorial02/#activating-models)
- [x] create migration file for your new model (the same link above)

**Comment by maryamyasaei** [comment]
I have this error  (No module named "allauth" ) when creating app.!!!!

**Comment by hesamd** [comment]
you need to rebuild your docker images, or install all the application by running, `docker-compose run web pip install -r requirement.txt`

**Comment by maryamyasaei** [comment]
now, I have could not open requirement file.

**Comment by maryamyasaei** [comment]
when I want to run a command to create an app , still I have this " No Module named "allauth" !!!!

**Comment by hesamd** [comment]
I thought we fixed this on your computer, next time let me know so I can take a look

**Comment by maryamyasaei** [comment]
I have this error while creating migration 
![screenshot from 2018-07-12 10-37-54](https://user-images.githubusercontent.com/28941044/42606237-bf27e0b8-85bf-11e8-8ef8-a5a40f90ec06.png)
