### ISSUE TITLE
Shortstories index view

### ISSUE THREAD

**Issue by hesamd** [evenset/ketabdan-project#29]
- [x] Write a simple index view to list all short stories [guide](https://docs.djangoproject.com/en/2.0/intro/tutorial03/)
- [x] Include the view in your urls
- [x] Push your code app and ask for a review
- [x] Add a template and load all your shortstories in html, use Bootstrap grid systems [Bootstrap](https://getbootstrap.com/docs/4.0/layout/grid/)
- [x] Edit the view to order short stories by publication date
- [x] Add short stories link to the navbar

**Comment by maryamyasaei** [comment]
what do you mean by list all shortstories? all fields we defined in models?

**Comment by hesamd** [comment]
yes
